### ISSUE TITLE
List page : wikipage redirections are listed in lists possibilities

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/RecordWizard#2]
I moved `List:Cmn/swadesh` to `List:Cmn/Swadesh`.
In the record wizard, this choices appears : 
![screenshot from 2018-05-21 12-20-25](https://user-images.githubusercontent.com/1420189/40303101-bc4fa174-5cf1-11e8-8e9c-efa7e162bafa.png)

Both can be selected and return rightfully the content of `List:Cmn/Swadesh`.

**Comment by 0x010C** [comment]
This is the expected behaviour. This allow to have two names for the same list, which can be usefull in some particular cases. If you don't want the old name to appear, ask an admin to delete it :wink:.

Just a note to tell you that issues are moved for now on on the Wikimedia Phabricator issue tracker: https://phabricator.wikimedia.org/project/view/3393/
