### ISSUE TITLE
Add possibility to provide additional metadata

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/RecordWizard#3]
### Sources
As for the `List` namespace, my sources often have rich data, most notably the English value : 
![screenshot from 2018-05-21 12-38-03](https://user-images.githubusercontent.com/1420189/40303637-da40f8b6-5cf3-11e8-8ab4-c3f46bf41d92.png)
![screenshot from 2018-05-21 12-28-57](https://user-images.githubusercontent.com/1420189/40303638-da577636-5cf3-11e8-86f9-5867acf03c39.png)

I currently manually remove these valuable data.

![screenshot from 2018-05-21 12-39-01](https://user-images.githubusercontent.com/1420189/40303655-f8e3b3da-5cf3-11e8-834d-e2948bd7331c.png)

### Current
Rather than : 
```
#	我
#	你
#	您
#	他
#	我們
#	你們
```

### Proposal
A proposition would be to recognize `tsv` list such :

```
#	[item:我]	[simplified:我]	[pinyin:wǒ]	[IPA:uɔ˨˩˦]	[eng:I]
#	[item:你]	[simplified:你]	[pinyin:nǐ]	[IPA:ni˨˩˦]	[eng:you]
#	[item:您]	[simplified:您]	[pinyin:nín]	[IPA:nin˧˥]	[eng:you (polite)]
#	[item:他]	[simplified:他]	[pinyin:tā]	[IPA:tʰa˥˥]	[eng:he]
#	[item:我們]	[simplified:我们]	[pinyin:wǒmen]	[IPA:uɔ˨˩mən]	[eng:we]
#	[item:你們]	[simplified:你们]	[pinyin:nǐmen]	[IPA:ni˨˩mən]	[eng:you]
```

Record the 2 column, forward the metadata in the ogg.

**Comment by 0x010C** [comment]
Generators are already able to add some metadatas to words, but those aren't visible during the record. This proposal goes in the same way as https://phabricator.wikimedia.org/T195952, could you add a comment there if you feel that the considered solution is not enough?

Just a note to tell you that I'm closing this issues because they are moved for now on on the Wikimedia Phabricator issue tracker: https://phabricator.wikimedia.org/project/view/3393/
